# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit_search', '0002_auto_20191023_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
