# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit_search', '0003_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonprofit',
            old_name='mission',
            new_name='impact',
        ),
    ]
